### ISSUE TITLE
mailbox.item.attachments[i].$0_0 is undefined

### ISSUE THREAD

**Issue by eloekset** [OfficeDev/Outlook-Add-in-JavaScript-GetAttachments#1]
The attachment object may have changed since this project was created. When I clone and run this in the browser today, I get an error when handling JSON for the attachment object. 

I found that it happens because the $0_0 property is undefined, and the properties needed are available under the _data$p$0 property. I've modified the code and will send a PR.
![attachmentexampleerror_1](https://cloud.githubusercontent.com/assets/791721/18171646/f892285a-7062-11e6-851e-0898a487cc0d.png)

**Comment by nigel-dewar** [comment]
I am still getting undefined even when there is an attachment. Has this sample been fixed?

**Comment by eloekset** [comment]
@nigel-dewar The pull request "Fix for issue 1" hasn't been merged yet. But if you take a look at it, you'll see the changes I did to make it work.

**Comment by nigel-dewar** [comment]
Thank you. I will update mine as u did. Cheers for posting me on this.

Nige.


Sent from Samsung Mobile


-------- Original message --------
From: Eivind Gussiås Løkseth
Date:22/12/2016 17:15 (GMT+10:00)
To: OfficeDev/Outlook-Add-in-JavaScript-GetAttachments
Cc: nigel-dewar , Mention
Subject: Re: [OfficeDev/Outlook-Add-in-JavaScript-GetAttachments] mailbox.item.attachments[i].$0_0 is undefined (#1)


@nigel-dewar<https://github.com/nigel-dewar> The pull request "Fix for issue 1" hasn't been merged yet. But if you take a look at it, you'll see the changes I did to make it work.

-
